# Generated by Django 5.0.6 on 2024-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0002_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='enContrat',
            field=models.BooleanField(default=False),
        ),
    ]
