# Generated by Django 5.0.6 on 2024-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='chauffeur',
        ),
        migrations.AddField(
            model_name='moto',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
